from .models import Category, Subcategory


def initialize_categories_and_subcategories():
    # Code that requires Category and Subcategory models
    categories = {
        "Books": [
            "Fiction",
            "Non-fiction",
            "Biographies",
            "Children's Books",
            "Educational",
            "Cookbooks",
            "Graphic Novels",
            "Mystery",
            "Fantasy",
            "Science Fiction",
            "Romance",
            "History",
            "Poetry",
            "Business",
            "Self-help",
        ],
        "Electronics": [
            "Smartphones",
            "Tablets",
            "Laptops",
            "Desktops",
            "Televisions",
            "Cameras",
            "Headphones",
            "Speakers",
            "Smartwatches",
            "Drones",
            "Gaming Consoles",
            "Accessories",
        ],
        "Furniture": [
            "Sofas",
            "Chairs",
            "Beds",
            "Tables",
            "Desks",
            "Cabinets",
            "Shelves",
            "Dressers",
            "Outdoor Furniture",
            "Lighting",
            "Rugs",
            "Home Decor",
        ],
        "Clothing": [
            "T-Shirts",
            "Shirts",
            "Pants",
            "Jeans",
            "Skirts",
            "Dresses",
            "Jackets",
            "Coats",
            "Sweaters",
            "Activewear",
            "Undergarments",
            "Swimwear",
            "Accessories",
            "Footwear",
        ],
        "Services": [
            "Home Cleaning",
            "Lawn Care",
            "Handyman",
            "Pest Control",
            "Plumbing",
            "Electrical",
            "Tutoring",
            "Photography",
            "Catering",
            "Event Planning",
            "Graphic Design",
            "Web Development",
            "Personal Training",
            "Pet Services",
        ],
        "Vehicles": [
            "Cars",
            "Trucks",
            "SUVs",
            "Vans",
            "Motorcycles",
            "Scooters",
            "Bicycles",
            "Boats",
            "RVs",
            "Trailers",
            "Aircraft",
            "Parts & Accessories",
        ],
        "Other": [
            "Antiques",
            "Collectibles",
            "Art",
            "Crafts",
            "Tools",
            "Musical Instruments",
            "Sports Equipment",
            "Toys & Games",
            "Gardening Supplies",
            "Pet Supplies",
            "Health & Beauty",
            "Office Supplies",
        ],
    }

    for category_name, subcategory_names in categories.items():
        category, _ = Category.objects.get_or_create(name=category_name)

        for subcategory_name in subcategory_names:
            Subcategory.objects.get_or_create(name=subcategory_name, category=category)
