version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=UniHub
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_AUTH0_DOMAIN=unihub.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=DRg9PEANganm7uLxXeJSawOo8r3M84BL
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./nginx/ssl/privkey.pem:/etc/ssl/certs/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

networks:
  default:
    name: app_network

volumes:
  db_data:
